// Build-time CHANGELOG.md parser. Emits `src/version.generated.ts`
// (gitignored) with version constants consumed by the runtime.
//
// CHANGELOG format (Keep a Changelog):
//   ## [X.Y.Z] - YYYY-MM-DD              ← released entry
//   ## [Unreleased] - next: minor        ← optional bump hint (patch|minor|major)
//
// If [Unreleased] has content, PACKAGE_VERSION = `${bumped}-dev` (hint
// applied to the latest released version; defaults to patch).

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

type BumpType = 'patch' | 'minor' | 'major';

interface ParseResult {
    packageVersion: string;
    packageVersionReleased: string;
    hasUnreleasedChanges: boolean;
    nextBumpType: BumpType | null;
}

const RELEASED_HEADER = /^## \[?(\d+)\.(\d+)\.(\d+)\]? - \d{4}-\d{2}-\d{2}/m;
const UNRELEASED_HEADER = /^## \[Unreleased\](?: - next: (patch|minor|major))?\s*$/m;

function parseChangelog(content: string): ParseResult {
    const releasedMatch = content.match(RELEASED_HEADER);

    if (!releasedMatch) {
        throw new Error(
            '[generate-version] No released entry found in CHANGELOG.md. '
            + 'Expected header `## [X.Y.Z] - YYYY-MM-DD` (or legacy `## X.Y.Z - YYYY-MM-DD`).'
        );
    }

    const [, majStr, minStr, patchStr] = releasedMatch;
    const major = Number(majStr);
    const minor = Number(minStr);
    const patch = Number(patchStr);
    const packageVersionReleased = `${major}.${minor}.${patch}`;

    const unreleasedHeaderMatch = content.match(UNRELEASED_HEADER);

    if (!unreleasedHeaderMatch) {
        return {
            packageVersion: packageVersionReleased,
            packageVersionReleased,
            hasUnreleasedChanges: false,
            nextBumpType: null
        };
    }

    // Slice between Unreleased header and next `## ` header to
    // check whether the section has any non-whitespace content.
    const startIdx = (unreleasedHeaderMatch.index ?? 0) + unreleasedHeaderMatch[0].length;
    const restAfterUnreleased = content.slice(startIdx);
    const nextHeaderIdx = restAfterUnreleased.search(/^## /m);
    const unreleasedBody = nextHeaderIdx >= 0
        ? restAfterUnreleased.slice(0, nextHeaderIdx)
        : restAfterUnreleased;
    const hasContent = /\S/.test(unreleasedBody);

    if (!hasContent) {
        return {
            packageVersion: packageVersionReleased,
            packageVersionReleased,
            hasUnreleasedChanges: false,
            nextBumpType: null
        };
    }

    const hint = (unreleasedHeaderMatch[1] as BumpType | undefined) ?? 'patch';
    let bumpedMajor = major;
    let bumpedMinor = minor;
    let bumpedPatch = patch;

    if (hint === 'major') {
        bumpedMajor = major + 1;
        bumpedMinor = 0;
        bumpedPatch = 0;
    } else if (hint === 'minor') {
        bumpedMinor = minor + 1;
        bumpedPatch = 0;
    } else {
        bumpedPatch = patch + 1;
    }

    const packageVersion = `${bumpedMajor}.${bumpedMinor}.${bumpedPatch}-dev`;

    return {
        packageVersion,
        packageVersionReleased,
        hasUnreleasedChanges: true,
        nextBumpType: hint
    };
}

function emit(result: ParseResult, outputPath: string): void {
    const banner = '// AUTO-GENERATED by scripts/generate-version.ts — DO NOT EDIT.\n\n';

    const body
        = `export const PACKAGE_VERSION = ${JSON.stringify(result.packageVersion)};\n`
        + `export const PACKAGE_VERSION_RELEASED = ${JSON.stringify(result.packageVersionReleased)};\n`
        + `export const HAS_UNRELEASED_CHANGES = ${JSON.stringify(result.hasUnreleasedChanges)};\n`
        + `export const NEXT_BUMP_TYPE = ${
            result.nextBumpType === null ? 'null' : JSON.stringify(result.nextBumpType)
        } as ${result.nextBumpType === null ? "null | 'patch' | 'minor' | 'major'" : "'patch' | 'minor' | 'major'"};\n`;

    writeFileSync(outputPath, banner + body, 'utf8');
}

export function generateVersion(rootDir: string): ParseResult {
    const changelogPath = resolve(rootDir, 'CHANGELOG.md');
    const outputPath = resolve(rootDir, 'src/version.generated.ts');
    const content = readFileSync(changelogPath, 'utf8');
    const result = parseChangelog(content);
    emit(result, outputPath);

    return result;
}

export { parseChangelog };

// CLI entry — guard prevents side effects on `import`.
const isMainModule
    = typeof process !== 'undefined'
    && process.argv[1]
    && import.meta.url === new URL(process.argv[1], 'file://').href;

if (isMainModule) {
    const rootDir = resolve(process.cwd());
    const result = generateVersion(rootDir);
    // eslint-disable-next-line no-console
    console.log(
        `[generate-version] emitted src/version.generated.ts → `
        + `PACKAGE_VERSION=${result.packageVersion}`
        + ` PACKAGE_VERSION_RELEASED=${result.packageVersionReleased}`
        + ` HAS_UNRELEASED_CHANGES=${result.hasUnreleasedChanges}`
        + ` NEXT_BUMP_TYPE=${result.nextBumpType ?? 'null'}`
    );
}
