import { getImagePath, ImageSize, TestImage } from './imagesData.js';

export enum MetricsTypes {
    charactersCount = 'charactersCount',
    wordCount = 'wordCount',
    editorialScore = 'editorialScore',
    tagsCount = 'tagsCount',
    topicsCount = 'topicsCount',
}

export type Metrics = Record<MetricsTypes, number | null>;

export interface StoriesData {
    id: string;
    title: string;
    image: string | null;
    modificationTime: string;
    kind: string | null;
    author: string | null;
    source: string | null;
    flags: string[];
    topics: string[];
    workflowStage: {
        name: string;
        color: string;
    };
    status: string;
    metrics: Metrics;
}

export const storiesData: StoriesData[] = [
    {
        id: '915bc9a8-32ca-4534-b931-d8133198a7fe',
        title: 'Microscope',
        image: getImagePath(TestImage.ANIMAL, ImageSize.SMALL),
        modificationTime: '2025-01-15T08:00:56Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: [],
        topics: ['News'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 501,
            wordCount: 42,
            editorialScore: 43,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '886da59e-aea4-4b2b-ae63-79792f4b0335',
        title: 'Python on the loose',
        image: getImagePath(TestImage.APARTMENT, ImageSize.SMALL),
        modificationTime: '2025-01-14T15:55:33Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: [],
        topics: [
            'Reptiles',
            'Newsweek Polska 5/2018',
            'python',
            'snakes',
            'Europe',
            'Asia',
            'North America',
            'South America',
            'Reptile Exhibition',
            'News',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'WITHDRAWN',
        metrics: {
            charactersCount: 407,
            wordCount: 41,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 10,
        },
    },
    {
        id: '310ce659-f19e-46be-a174-8124fe4ea546',
        title: 'Test',
        image: null,
        modificationTime: '2025-01-13T15:02:30Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: [],
        topics: [],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'NEW',
        metrics: {
            charactersCount: 0,
            wordCount: 0,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 0,
        },
    },
    {
        id: '4336a1a2-d483-467a-927f-69f41c464ebf',
        title: 'Focal Point examples',
        image: getImagePath(TestImage.CAR, ImageSize.SMALL),
        modificationTime: '2025-01-13T10:58:56Z',
        kind: 'Article',
        author: 'Arkadiusz Staroń',
        source: 'Ring Publishing',
        flags: ['Hidden'],
        topics: ['Images'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 260,
            wordCount: 49,
            editorialScore: 57,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '7d13011e-d9b9-45e1-a512-2b547d390bf5',
        title: 'Snake gallery',
        image: getImagePath(TestImage.DAN, ImageSize.SMALL),
        modificationTime: '2024-12-18T07:32:09Z',
        kind: 'Gallery',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Reptiles', 'Brand  Ring', 'Reptile Exhibition', 'Comments', 'snakes', 'Editor', 'Writer'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 143,
            wordCount: 24,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 7,
        },
    },
    {
        id: 'acd490b4-da5a-455a-b802-08495f40b029',
        title: 'Table test - Laureaci Diamentów Forbesa 2021 - woj. mazowieckie',
        image: getImagePath(TestImage.DOG, ImageSize.SMALL),
        modificationTime: '2024-12-13T07:31:00Z',
        kind: 'Article',
        author: 'test',
        source: 'Pulse',
        flags: ['Hidden', 'No ads'],
        topics: ['News'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 53593,
            wordCount: 8487,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '6b78bfe9-d71f-4ad9-9e79-5e09fede9eb5',
        title: 'Procolobus kirkii',
        image: getImagePath(TestImage.BEACH, ImageSize.SMALL),
        modificationTime: '2024-12-09T12:08:06Z',
        kind: 'Article',
        author: 'A.S.',
        source: 'Wikipedia',
        flags: ["Editor's choice (deprecated)", 'No ads'],
        topics: ['Animals', 'Mammals', 'Albert Brooks'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 644,
            wordCount: 112,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 3,
        },
    },
    {
        id: '547f49ba-b416-4860-939e-fcd9b4bd0fbe',
        title: 'Video test',
        image: getImagePath(TestImage.BIRD, ImageSize.SMALL),
        modificationTime: '2024-12-09T12:04:19Z',
        kind: 'Video',
        author: null,
        source: 'AI Generated',
        flags: [],
        topics: ['Reptiles'],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'NEW',
        metrics: {
            charactersCount: 0,
            wordCount: 0,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '1a264d32-8c69-4104-ada1-678d93b78e47',
        title: 'Covid-19 - Template',
        image: getImagePath(TestImage.BIRD_2, ImageSize.SMALL),
        modificationTime: '2024-12-09T12:03:59Z',
        kind: 'Gallery',
        author: null,
        source: 'Ring Publishing',
        flags: ['Hidden'],
        topics: ['Testowy raport'],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'NEW',
        metrics: {
            charactersCount: 0,
            wordCount: 0,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '4ff8688c-60e6-4204-821d-82a7b367ab9e',
        title: 'fghg',
        image: null,
        modificationTime: '2024-12-09T06:57:59Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['News'],
        topics: ['Mobile Content App'],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'NEW',
        metrics: {
            charactersCount: 67,
            wordCount: 12,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: 'c91c6c2c-d3be-4697-8baf-94332d315555',
        title: 'Article with picture',
        image: getImagePath(TestImage.BIRD_3, ImageSize.SMALL),
        modificationTime: '2024-12-03T07:52:31Z',
        kind: 'Article',
        author: 'Dennis Scott',
        source: 'Pulse',
        flags: ['No ads'],
        topics: ['Pulse2Demo'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 10,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '41675c66-8749-483f-8fc8-274e712d8359',
        title: 'AnimaQuiz',
        image: getImagePath(TestImage.BIRD_3, ImageSize.SMALL),
        modificationTime: '2024-11-28T19:58:38Z',
        kind: 'Quiz',
        author: null,
        source: 'Pulse',
        flags: ['Hidden', 'No ads'],
        topics: ['Animals'],
        workflowStage: { name: 'Test1', color: '#000000' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 19,
            wordCount: 4,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: 'd2e3935d-01e8-4d8e-b10d-c526a149d537',
        title: 'Best Mammal',
        image: getImagePath(TestImage.ANIMAL, ImageSize.SMALL),
        modificationTime: '2024-11-28T19:58:19Z',
        kind: 'Poll',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals'],
        workflowStage: { name: 'Test1', color: '#000000' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 19,
            wordCount: 3,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '9df0e317-9258-4532-946e-bd87fe80f46c',
        title: 'Marbled newt',
        image: getImagePath(TestImage.BIRD_3, ImageSize.SMALL),
        modificationTime: '2024-11-28T19:57:55Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Amphibians'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1479,
            wordCount: 205,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: 'a509a0e9-86db-4331-9ce4-fea8dbac568c',
        title: 'Warthog',
        image: getImagePath(TestImage.BIRD_4, ImageSize.SMALL),
        modificationTime: '2024-11-28T19:55:46Z',
        kind: null,
        author: null,
        source: 'Wikipedia',
        flags: ["Editor's choice (deprecated)", 'No ads'],
        topics: ['Animals'],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 676,
            wordCount: 109,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: 'e970fece-f074-439e-a851-8c2c669d149d',
        title: 'Extinct Cave Bear DNA Found in Living Bears',
        image: getImagePath(TestImage.BIRD_5, ImageSize.SMALL),
        modificationTime: '2024-11-28T19:55:46Z',
        kind: 'Article',
        author: 'Dominik',
        source: 'Pulse',
        flags: ['Hidden', 'No ads'],
        topics: ['Mammals'],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1107,
            wordCount: 179,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '9b83741a-8e31-4d12-b253-01a935c9d79c',
        title: 'Tell us what you think',
        image: getImagePath(TestImage.CAMERA, ImageSize.SMALL),
        modificationTime: '2024-11-28T19:55:46Z',
        kind: 'Poll',
        author: null,
        source: 'Pulse',
        flags: ['Hidden', 'No ads'],
        topics: ['News'],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 47,
            wordCount: 8,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '4b719962-df63-4797-999f-2d9d15a4bba9',
        title: 'Kodiak bear',
        image: getImagePath(TestImage.BEACH, ImageSize.SMALL),
        modificationTime: '2024-11-28T19:55:46Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals'],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 26254,
            wordCount: 4115,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '75037361-a89a-435a-bfcf-37886360b1be',
        title: 'Story with a lot of features.',
        image: getImagePath(TestImage.BOAT, ImageSize.SMALL),
        modificationTime: '2024-11-28T11:00:13Z',
        kind: 'Article',
        author: 'Adam Guz',
        source: 'Ring Publishing',
        flags: ['Disable autonext', "Editor's choice (deprecated)", 'Not news', 'No ads'],
        topics: [
            'Pulse2Demo',
            'News',
            'Reptiles',
            'Moszna Castle',
            'Algeria',
            'Mammals of North Africa',
            'Oscars 2021',
            'Wolverine',
            'Example of Deleted Tag',
            'Reptile Exhibition',
            'Business Insider Polska',
            'autoswiat.pl',
            'Divert me',
            'Give me perspective',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1217,
            wordCount: 176,
            editorialScore: null,
            tagsCount: 6,
            topicsCount: 14,
        },
    },
    {
        id: 'f3529c96-a01a-4f3b-a78e-d0e6f51f001d',
        title: 'Concurent Editting - test',
        image: getImagePath(TestImage.CASTLE, ImageSize.SMALL),
        modificationTime: '2024-11-27T09:41:09Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['Exclude from Aureus', 'No ads'],
        topics: ['News'],
        workflowStage: { name: 'Draft', color: '#EB1E32' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 152,
            wordCount: 36,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '992721fa-55d2-46bc-a754-0bf7b09c8669',
        title: 'Vulture',
        image: getImagePath(TestImage.LANDSCAPE, ImageSize.SMALL),
        modificationTime: '2024-11-21T17:13:16Z',
        kind: 'Article',
        author: 'John Doe',
        source: 'Wikipedia',
        flags: ['Mourning', 'No ads'],
        topics: ['Birds'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1614,
            wordCount: 223,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '355c7ef6-d405-46b2-ab1e-0ea2479681f3',
        title: 'Schedule test',
        image: getImagePath(TestImage.LANDSCAPE_3, ImageSize.SMALL),
        modificationTime: '2024-11-14T13:30:23Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: [],
        topics: ['Animals'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'NEW',
        metrics: {
            charactersCount: 10,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '831ca843-356f-4c39-8169-e78d62d99c00',
        title: 'Lots of animals',
        image: null,
        modificationTime: '2024-11-13T06:23:17Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['Hidden', 'No ads'],
        topics: ['Animals'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 36,
            wordCount: 8,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '660ef146-2228-41e2-a992-18063eb57188',
        title: 'Signature 4 - Team Work',
        image: null,
        modificationTime: '2024-11-05T14:09:34Z',
        kind: 'Article',
        author: 'Sir Davidson Attenborough',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Mammals'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 8,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '8a6ead7e-d317-4419-a86a-40c848757c67',
        title: 'Article from Neverland Times',
        image: null,
        modificationTime: '2024-11-05T12:45:49Z',
        kind: 'Article',
        author: null,
        source: 'Neverland Times',
        flags: ['No ads'],
        topics: ['News'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '7f12392f-4ff8-417d-96dd-2bfd7d213fde',
        title: 'Juxtapose',
        image: getImagePath(TestImage.LANDSCAPE_2, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:46Z',
        kind: 'Video',
        author: null,
        source: 'Pulse',
        flags: ['No ads'],
        topics: ['News'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 46,
            wordCount: 10,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '816074ad-d2f7-40ec-a63d-47b1e05229a9',
        title: 'Lorem ipsum',
        image: getImagePath(TestImage.LANDSCAPE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:46Z',
        kind: 'Article',
        author: 'Don John',
        source: 'Wikipedia',
        flags: ['Hidden', 'No ads'],
        topics: ['Pulse2Demo'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1335,
            wordCount: 201,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '26934fe4-0c14-4be0-8b86-c5b3894541d2',
        title: 'Pulse2 Editor Elements',
        image: null,
        modificationTime: '2024-11-05T12:45:46Z',
        kind: 'Article',
        author: 'Terry Pratchett',
        source: 'Pulse',
        flags: ['Hidden', 'No ads'],
        topics: ['News', 'Pulse2Demo'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 6674,
            wordCount: 1018,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 2,
        },
    },
    {
        id: '8ff94254-5608-432b-ab3e-42f710443b04',
        title: 'Story Editor - TopBar description',
        image: getImagePath(TestImage.TEXTURE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:46Z',
        kind: 'Article',
        author: null,
        source: 'Pulse',
        flags: ['Hidden', 'No ads'],
        topics: ['News'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 6279,
            wordCount: 968,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '2601fb4e-8411-447b-9e67-8e1b03e55670',
        title: 'Bengali language - সমস্ত মানুষ স্বাধীনভাবে সমান মর্যাদা এবং',
        image: getImagePath(TestImage.BUILDING, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:46Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['News'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 2063,
            wordCount: 267,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '946946a9-d52c-458f-b413-da1e70ae4892',
        title: 'Grizzly Bear',
        image: getImagePath(TestImage.ISLAND, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:45Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1382,
            wordCount: 133,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '6d3ccd33-696e-4f06-8c43-98ead41c8164',
        title: 'Forbes - tables4charts',
        image: getImagePath(TestImage.APARTMENT, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:45Z',
        kind: 'Article',
        author: null,
        source: 'Pulse',
        flags: ['Hidden', 'No ads'],
        topics: ['News'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 41409,
            wordCount: 7334,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '96c53831-b538-4c3e-bd39-13212c6a5a85',
        title: 'Monday morning',
        image: getImagePath(TestImage.BUILDING, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:44Z',
        kind: 'Quiz',
        author: null,
        source: 'DinoAnimals',
        flags: ['No ads'],
        topics: ['Appetizer'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 20,
            wordCount: 3,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: 'd3eae0e3-390b-436f-8ef5-787b323a5890',
        title: 'Grizzly Bears',
        image: getImagePath(TestImage.FARM, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:44Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1138,
            wordCount: 107,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: 'a76474a0-6b16-4831-a83c-e3b5a5a85484',
        title: 'Bookmarklet',
        image: getImagePath(TestImage.ISLAND, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:44Z',
        kind: 'Article',
        author: null,
        source: 'Pulse',
        flags: ['Hidden', 'No ads'],
        topics: ['Pulse2Demo', 'Mammals'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 20,
            wordCount: 5,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 2,
        },
    },
    {
        id: 'e2402b23-3050-4a20-867f-e2b4766ed43d',
        title: 'Northwest Reptile Expo',
        image: getImagePath(TestImage.FOREST, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:44Z',
        kind: 'Article',
        author: null,
        source: 'Northwest Reptile Expos',
        flags: ['Hidden', 'No ads'],
        topics: ['Reptiles'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 487,
            wordCount: 78,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '399b105d-b1f3-4de5-8124-7fc622571692',
        title: 'Publish or not',
        image: getImagePath(TestImage.FARM, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:44Z',
        kind: 'Article',
        author: null,
        source: 'Life of Crocodile',
        flags: ['No ads'],
        topics: ['Pulse2Demo'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 23,
            wordCount: 4,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '1278b3d0-3578-484c-9d7b-744f3a21ac8f',
        title: 'Auto publish',
        image: getImagePath(TestImage.MOOSE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:43Z',
        kind: 'Article',
        author: null,
        source: 'Life of Crocodile',
        flags: ['No ads'],
        topics: ['Pulse2Demo'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 61,
            wordCount: 16,
            editorialScore: null,
            tagsCount: 0,
            topicsCount: 1,
        },
    },
    {
        id: '9bc1239d-aef8-4eb9-8154-68fa2b6b38c2',
        title: 'Elephant',
        image: getImagePath(TestImage.MOUNTAINS, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:42Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'Mammals in Europe'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 13485,
            wordCount: 1322,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'c364efe5-9dc9-4fef-8767-950e80794c23',
        title: 'Marbled polecat',
        image: getImagePath(TestImage.MOUNTAINS, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:41Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: [
            'Mammals',
            'Animals',
            'IUCN Red List vulnerable species',
            'Mustelinae',
            'Carnivorans of Asia',
            'Carnivorans of Europe',
            'Mammals of Central Asia',
            'Mammals of Azerbaijan',
            'Mammals of China',
            'Mammals in Europe',
            'Mammals of the Middle East',
            'Mammals of Pakistan',
            'Mammals of Western Asia',
            'Vulnerable animals',
            'Vulnerable fauna of Asia',
            'Vulnerable biota of Europe',
            'Mammals described in 1770',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 10529,
            wordCount: 1449,
            editorialScore: null,
            tagsCount: 15,
            topicsCount: 17,
        },
    },
    {
        id: '5d124a0f-b4a1-4f60-b0c3-43301874eb52',
        title: 'Wolverine',
        image: getImagePath(TestImage.MOUNTAINS_2, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:41Z',
        kind: 'Article',
        author: 'Jatin Sindhu',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'Breathable', 'Strong', 'Furry', 'Dangerous', 'Wild'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1263,
            wordCount: 141,
            editorialScore: null,
            tagsCount: 5,
            topicsCount: 6,
        },
    },
    {
        id: 'fed153b0-e8f7-4953-82c0-edeed45e9518',
        title: 'Publishing the story - Breaking news scenario',
        image: null,
        modificationTime: '2024-11-05T12:45:41Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'Tutorials', 'Stories'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1612,
            wordCount: 247,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 3,
        },
    },
    {
        id: '89ecca0f-d265-437a-b625-01f7748b20aa',
        title: 'Honey badgers',
        image: getImagePath(TestImage.PERSON, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:41Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['News', 'South Asia', 'Africa', 'Mammals of the Middle East'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 6357,
            wordCount: 907,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 4,
        },
    },
    {
        id: '08c0a471-306d-433e-b5b2-708f403c6d67',
        title: 'Frankfurt am Man Airport',
        image: null,
        modificationTime: '2024-11-05T12:45:41Z',
        kind: 'Article',
        author: null,
        source: 'BBC.com',
        flags: ['No ads'],
        topics: ['Living', 'AC Sparta Praha'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 600,
            wordCount: 39,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'd190dce4-e81f-4c61-909f-7b8e2269226e',
        title: 'Embeding external content to the Story',
        image: null,
        modificationTime: '2024-11-05T12:45:41Z',
        kind: 'Article',
        author: 'Arkadiusz Staroń',
        source: 'Ring Publishing',
        flags: ['Hidden', "Editor's choice (deprecated)", 'No ads'],
        topics: ['Story Editor', 'Tutorials', 'Embeds'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 792,
            wordCount: 115,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 3,
        },
    },
    {
        id: 'a3c84b7b-31d0-4c7c-b424-7c70379e5aa1',
        title: 'tytuł',
        image: null,
        modificationTime: '2024-11-05T12:45:41Z',
        kind: 'Article',
        author: 'Wiki',
        source: 'Pulse',
        flags: ['No ads'],
        topics: ['News', 'tag'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 6,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '085ce9ff-07ba-488f-bcdf-dc2ccf86f7ec',
        title: 'Quiz',
        image: null,
        modificationTime: '2024-11-05T12:45:39Z',
        kind: 'Quiz',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Content Ring', 'test'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 15,
            wordCount: 2,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '509b170a-e37d-4237-8120-f2de1b3c7d3d',
        title: 'Story',
        image: null,
        modificationTime: '2024-11-05T12:45:39Z',
        kind: 'Article',
        author: null,
        source: 'Pulse',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'test'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 33,
            wordCount: 5,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'e3bdd6c4-4beb-4301-8b07-d81f2abc8df4',
        title: 'jaskółka',
        image: null,
        modificationTime: '2024-11-05T12:45:39Z',
        kind: 'Quiz',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Birds', 'Wild animal'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 37,
            wordCount: 6,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '03ee6674-13f4-4e59-b14a-f145389962bf',
        title: 'Alpine ibex',
        image: getImagePath(TestImage.MOUNTAINS_2, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:39Z',
        kind: 'Article',
        author: 'Don John',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: [
            'Mammals',
            'Mammals described in 1935',
            'Fauna of the Himalayas',
            'Mammals of Costa Rica',
            'Mammals in Europe',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1498,
            wordCount: 193,
            editorialScore: null,
            tagsCount: 4,
            topicsCount: 5,
        },
    },
    {
        id: '2de2f033-db9d-46ea-a8e6-39057a867c57',
        title: 'Himalayan brown bear',
        image: getImagePath(TestImage.CAR_4, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:39Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: [
            'Mammals',
            'IUCN Red List critically endangered species',
            'Bears',
            'Carnivorans of Asia',
            'Fauna of the Himalayas',
            'Mammals of Pakistan',
            'Mammals of India',
            'Mammals of Nepal',
            'Mammals of Bhutan',
            'Fauna of Jammu and Kashmir',
            'Critically endangered biota of Asia',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 3851,
            wordCount: 572,
            editorialScore: null,
            tagsCount: 10,
            topicsCount: 11,
        },
    },
    {
        id: '061bace2-ec84-4f6b-9935-bdb577470ed0',
        title: 'RE: 10 films to watch this February',
        image: null,
        modificationTime: '2024-11-05T12:45:39Z',
        kind: 'Reply',
        author: 'Arkadiusz Staroń',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'sci-fi'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 102,
            wordCount: 19,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'f6155cb3-5988-4d76-a8d0-025acba6423d',
        title: 'Managing content on your HomePage',
        image: null,
        modificationTime: '2024-11-05T12:45:36Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Tutorials', 'Editoral Lists'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1013,
            wordCount: 170,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '91bab3c4-7af0-4529-9183-77160b6ca74e',
        title: 'Red deer',
        image: getImagePath(TestImage.TREE_2, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:35Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: [
            'Mammals',
            'IUCN Red List least concern species',
            'Cervus',
            'Elk and red deer',
            'Mammals in Europe',
            'Mammals of North Africa',
            'Mammals of Central Asia',
            'Mammals of Western Asia',
            'Invasive animal species in the United States',
            'National symbols of the Republic of Ireland',
            'National symbols of Ireland',
            'Mammals described in 1758',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 24676,
            wordCount: 3979,
            editorialScore: null,
            tagsCount: 11,
            topicsCount: 12,
        },
    },
    {
        id: '431f2467-fbd4-44a7-9b1c-29572cd645a5',
        title: 'Article embedów',
        image: getImagePath(TestImage.TREE_3, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:35Z',
        kind: 'Article',
        author: null,
        source: 'Pulse',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'Mammals in Europe'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 50,
            wordCount: 7,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '8cb20af7-8c9b-494d-8f05-180f713cbd9d',
        title: 'Onet StyleBook Check',
        image: getImagePath(TestImage.TREE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:35Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'examples'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1417,
            wordCount: 204,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'd2673bcd-c5ed-401d-8d1a-f9a9008128e6',
        title: 'Article',
        image: null,
        modificationTime: '2024-11-05T12:45:35Z',
        kind: 'Article',
        author: 'Steve Irwin',
        source: 'AFP',
        flags: ['No ads'],
        topics: ['Amphibians', 'AC Sparta Praha'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 0,
            wordCount: 0,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '629c6f8d-9b65-4bdb-a83b-cc7d8c2b2e88',
        title: 'kdlkdla',
        image: null,
        modificationTime: '2024-11-05T12:45:33Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'test 111133344'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 5,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'bfb8180e-dbd2-4d16-bb7e-2575a4d9647f',
        title: 'Baltimore oriole.',
        image: getImagePath(TestImage.STAIRS, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:33Z',
        kind: 'Article',
        author: 'Wiki',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Birds', 'Breathable', 'Flying', 'Yellow', 'Small'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1701,
            wordCount: 281,
            editorialScore: null,
            tagsCount: 4,
            topicsCount: 5,
        },
    },
    {
        id: '26fba4a3-86aa-4885-b9de-65da7dbf8ca4',
        title: 'RE: 10 films to watch this February (alt version)',
        image: null,
        modificationTime: '2024-11-05T12:45:33Z',
        kind: 'Reply',
        author: 'Arkadiusz Staroń',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'sci-fi'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 319,
            wordCount: 54,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '92137cc9-9fd2-4859-baca-ffc66fad93d1',
        title: 'Golden Hamster',
        image: getImagePath(TestImage.ANIMAL, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:33Z',
        kind: 'Article',
        author: 'Arkadiusz Staroń',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'Exclusive', 'pets'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 2866,
            wordCount: 322,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 3,
        },
    },
    {
        id: '80ad8d58-7082-4c02-b52b-4ee05a744c66',
        title: 'Wombat',
        image: getImagePath(TestImage.BUILDING, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:33Z',
        kind: 'Article',
        author: 'Wojciech Krzyżyk',
        source: 'Wikipedia',
        flags: ["Editor's choice (deprecated)", 'No forum', 'No ads'],
        topics: ['Mammals', 'Pulse2Demo', 'Furry', 'Diprotodontia'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4507,
            wordCount: 718,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 4,
        },
    },
    {
        id: 'ba1fbb1f-63a7-42de-83db-9680fc479e3c',
        title: 'Rattlesnake',
        image: getImagePath(TestImage.STREET_3, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:33Z',
        kind: 'Article',
        author: 'Arkadiusz Staroń',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Reptiles', 'snakes'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1487,
            wordCount: 225,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '94ed9306-a3ea-4a09-a841-d2231b84affe',
        title: 'Sprat',
        image: getImagePath(TestImage.STREET, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:32Z',
        kind: null,
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['ryby2', 'Fishes 2'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4553,
            wordCount: 740,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '4abb6088-5ce3-41eb-9612-0d2242f888f5',
        title: 'Glass frog',
        image: getImagePath(TestImage.SEA, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:32Z',
        kind: null,
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['frogs', 'Amphibians'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4460,
            wordCount: 526,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'c9d33321-35a1-43e9-94aa-26393ec3d64a',
        title: 'Story',
        image: null,
        modificationTime: '2024-11-05T12:45:32Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'Embeds'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 53,
            wordCount: 9,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '520bd6d8-eaec-42f7-a82b-df4d5fa81f6e',
        title: 'Chameleon',
        image: getImagePath(TestImage.TEXTURE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:32Z',
        kind: 'Video',
        author: 'Wiki',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Living', 'Breathable', 'Funny'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1387,
            wordCount: 211,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 3,
        },
    },
    {
        id: '3f43ab61-971b-44cf-8105-f2ee31ad8be7',
        title: 'Lamas - a breathtaking [LISTICLE]',
        image: getImagePath(TestImage.CHRISTMAS_TREE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:31Z',
        kind: 'Listicle',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'News', 'Furry', 'Funny'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 3633,
            wordCount: 585,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 4,
        },
    },
    {
        id: 'c743099d-4379-4e18-b383-dd10bd3e02d4',
        title: 'Adding images to the story.',
        image: getImagePath(TestImage.KITCHEN, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:31Z',
        kind: 'Article',
        author: 'Arkadiusz Staroń',
        source: 'Ring Publishing',
        flags: ["Editor's choice (deprecated)", 'Hidden', 'No ads'],
        topics: ['Story Editor', 'Tutorials', 'Images'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 520,
            wordCount: 76,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 3,
        },
    },
    {
        id: '6ea2423f-4c56-48b5-9ebd-79f73a18f668',
        title: 'Story about a small pretty bird...',
        image: getImagePath(TestImage.ORCHARD, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:31Z',
        kind: null,
        author: 'Jatin Sindhu',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Small', 'Birds'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 62,
            wordCount: 11,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '8b98336a-f797-4f1b-b37d-0dc4d5ce941d',
        title: 'Blue jay',
        image: getImagePath(TestImage.LIVING_ROOM, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:30Z',
        kind: 'Article',
        author: 'Wiki',
        source: 'Wikipedia',
        flags: ['Not news', 'No ads'],
        topics: ['Birds', 'Breathable', 'Flying'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1459,
            wordCount: 244,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 3,
        },
    },
    {
        id: '65bf6f10-c997-4d9a-84fd-8ac1f2546deb',
        title: 'Wolves',
        image: getImagePath(TestImage.ANIMAL, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:45:30Z',
        kind: 'Article',
        author: 'John Doe',
        source: 'Wikipedia',
        flags: ['Adult only', 'No ads'],
        topics: ['Mammals', 'Wild animal'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 34,
            wordCount: 7,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '6a938b2f-c247-47a0-a071-9c44f4285a59',
        title: 'Cracow',
        image: getImagePath(TestImage.ISLAND, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: 'test',
        source: 'Pulse',
        flags: ["Editor's choice (deprecated)", 'No forum', 'No ads'],
        topics: [
            'News',
            'Kraków test',
            'kraków test 2',
            'kraków test 3',
            'kraków test 4',
            'KRAKÓW',
            'kraków test 5',
            'Newsletter',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 101,
            wordCount: 16,
            editorialScore: null,
            tagsCount: 6,
            topicsCount: 8,
        },
    },
    {
        id: 'd238cc1c-b0d3-4e23-a4b2-4936e274c940',
        title: 'Zmarł kilkanaście godzin po interwencji policji. Decyzja śledczych',
        image: null,
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'News', 'WIADOMOŚCI'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 5,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 3,
        },
    },
    {
        id: 'fdc2e9e1-822e-417f-99f0-1b1cdf85f5c5',
        title: 'Platypus',
        image: getImagePath(TestImage.DOG, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:39Z',
        kind: null,
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'rare', 'eggborne', 'sweet'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1658,
            wordCount: 262,
            editorialScore: null,
            tagsCount: 3,
            topicsCount: 4,
        },
    },
    {
        id: '2f72beba-bc67-4d06-aa37-ad9465748608',
        title: 'jw',
        image: null,
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: 'editor name - change test2',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Ad Server', 'Aktorka'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 9,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '436c47be-39fa-41be-b80a-acee7983d8b0',
        title: 'Story failed',
        image: getImagePath(TestImage.PERSON, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'kraków test 2'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 2,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '4dbc55fe-a93e-4357-9aee-8f6a95f14329',
        title: 'Story about my cat',
        image: getImagePath(TestImage.MOUNTAINS, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:39Z',
        kind: null,
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'Funny'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 33,
            wordCount: 8,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '9ceae7b4-4ff5-4a75-a981-02dbda0bb311',
        title: 'Hedgehog',
        image: getImagePath(TestImage.STREET_2, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'Wild animal', 'Newsletter'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1504,
            wordCount: 124,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 3,
        },
    },
    {
        id: 'c76341ae-94a4-480b-8b9a-b706e2c79f38',
        title: 'Last dance!',
        image: null,
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Animals', 'examples', 'Mammals of the Middle East'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 149,
            wordCount: 24,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 3,
        },
    },
    {
        id: '104a779e-022c-4b57-b825-6a31d6cb43d6',
        title: 'Niewidzialna broń Putina i Xi Jinpinga. Waszyngton przygotowuje się do walki ze śmiercionośnym zagrożeniem ze strony dyktatorów',
        image: null,
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'WIADOMOŚCI'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'dc6cba37-d6fd-471b-99b0-8b773aaaa615',
        title: 'yturtuytry',
        image: null,
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['News', 'Hidden', 'No ads'],
        topics: ['News', 'Story Editor'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 14,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'd898dc61-1588-418d-8586-960443fef59d',
        title: 'Lekarz ścigany przez Ziobrę: nękają mnie od 16 lat',
        image: null,
        modificationTime: '2024-11-05T12:44:39Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['Hidden', 'No ads'],
        topics: ['Pulse2Demo', 'WIADOMOŚCI'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '81244100-d0b2-4a48-ac51-91e01326d8b3',
        title: 'Szwecja przyjęta do NATO',
        image: getImagePath(TestImage.FOREST, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:37Z',
        kind: 'Article',
        author: 'Piotr Łęgowski',
        source: 'Ring Publishing',
        flags: ['News', 'No ads'],
        topics: ['News', 'NATO'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 569,
            wordCount: 78,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '324e083d-9f37-4d4c-a043-9027640381df',
        title: 'Story z gif',
        image: null,
        modificationTime: '2024-11-05T12:44:37Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Animals', 'Anas', 'Gatunek (biologia)'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 0,
            wordCount: 0,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 3,
        },
    },
    {
        id: 'a916e16d-f736-456b-b5a6-2aa70c3a88a6',
        title: 'Gwiazdy olśniły na Złotych Globach. Klum jak z żurnala, a Debicki zaliczyła wpadkę',
        image: null,
        modificationTime: '2024-11-05T12:44:37Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['Hidden', 'No ads'],
        topics: ['Pulse2Demo', 'WIADOMOŚCI'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'ffa03639-515a-4298-8a4c-e3f32b62c4b7',
        title: 'Deer Accident on The road',
        image: getImagePath(TestImage.TREE_3, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:37Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'Mammals', 'forest creature', 'Mammals of the Middle East'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1543,
            wordCount: 205,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 4,
        },
    },
    {
        id: '38031887-7e7b-4bbd-b608-9648223001d9',
        title: 'Story Wojtek-Rafał [2]',
        image: null,
        modificationTime: '2024-11-05T12:44:37Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Amphibians', 'AC Sparta Praha'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 16,
            wordCount: 2,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '36b6d6bd-a8bc-40f5-bc9a-4c6259c19e1c',
        title: 'Beaver',
        image: getImagePath(TestImage.FARM, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:37Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['Hidden', 'No forum', 'Sensitive', 'Table of contents', 'No ads'],
        topics: ['Mammals', 'rodent', 'woodcutterrr', 'mammal'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 3940,
            wordCount: 568,
            editorialScore: null,
            tagsCount: 3,
            topicsCount: 4,
        },
    },
    {
        id: '75744e68-1bf0-4387-bcc9-01866e05b46c',
        title: 'Antywojenna manifestacja w Warszawie',
        image: getImagePath(TestImage.JELLYFISH, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:37Z',
        kind: 'Liveblog',
        author: 'Piotr Łęgowski',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'Wojna w Ukrainie'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 167,
            wordCount: 20,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '7b22bd32-e526-4f87-8fed-74aa39e8de84',
        title: 'Embed Article',
        image: null,
        modificationTime: '2024-11-05T12:44:37Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Amphibians', 'AC Sparta Praha'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 0,
            wordCount: 0,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '75ad090e-f333-474d-83e0-61fa10259efe',
        title: 'Hot news! - edit 3',
        image: getImagePath(TestImage.APARTMENT, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:35Z',
        kind: 'Article',
        author: 'Piotr Łęgowski',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'testowy'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 59,
            wordCount: 2,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '70911722-1aa0-4726-9037-a2371d2dff34',
        title: 'Piranhaconda like Pinacolada',
        image: getImagePath(TestImage.CRAB, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:35Z',
        kind: 'News',
        author: 'Wiki',
        source: 'AFP',
        flags: ['No ads'],
        topics: [
            'Extinct',
            'Strong',
            'Funny',
            'Strange',
            'Cold blooded',
            'News',
            'Funny, Strange',
            'PASAŻEROWIE',
            'American Society of Mammalogists',
            'test',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 2945,
            wordCount: 445,
            editorialScore: null,
            tagsCount: 8,
            topicsCount: 10,
        },
    },
    {
        id: 'd170c237-e244-42a0-9755-b86b4838186e',
        title: 'White dog',
        image: getImagePath(TestImage.ANIMAL, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:32Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'canines', 'carnivores', 'mammals', 'Asia'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 77,
            wordCount: 13,
            editorialScore: null,
            tagsCount: 3,
            topicsCount: 5,
        },
    },
    {
        id: '6da43906-7483-4f1e-8dcf-7e259efd2272',
        title: 'POLSKA mistrzem polski!',
        image: getImagePath(TestImage.LIVING_ROOM, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:32Z',
        kind: 'Article',
        author: 'Piotr Łęgowski',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'birds', 'Turtles of Europe'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 69,
            wordCount: 11,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 3,
        },
    },
    {
        id: 'e66cd6bd-e675-4524-9928-3a21a7624efe',
        title: 'Rec oooooo',
        image: getImagePath(TestImage.DESERT, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:32Z',
        kind: 'Article',
        author: null,
        source: 'AI Generated',
        flags: ['No ads'],
        topics: ['Amphibians', 'Algeria'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 185,
            wordCount: 28,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '9bf2fd05-f24c-4e6b-9e04-cfe71b9f50e2',
        title: 'Program TV - Onet.pl',
        image: null,
        modificationTime: '2024-11-05T12:44:32Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'Anas'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 6,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: 'da9ea96b-eb39-47d8-bed0-4ceb79f63d52',
        title: 'Really cool Gallery',
        image: getImagePath(TestImage.EAGLE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:31Z',
        kind: 'Article',
        author: 'Piotr Łęgowski',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Birds', 'Landscapes'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 5,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '17b65bd7-4d59-4e9e-aeac-809491438cac',
        title: 'Urgent news',
        image: null,
        modificationTime: '2024-11-05T12:44:31Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'WIADOMOŚCI'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '99e73eb7-e7b6-4006-a77f-4aa7d39e3fe7',
        title: 'Huge gallery',
        image: getImagePath(TestImage.SEA, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:31Z',
        kind: 'Gallery',
        author: 'Arkadiusz Staroń',
        source: 'Ring Publishing',
        flags: ["Editor's choice (deprecated)", 'Hidden', 'No ads'],
        topics: ['Story Editor', 'examples', 'Editor', 'Writer'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 55,
            wordCount: 11,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 4,
        },
    },
    {
        id: 'e52cb499-3691-4cb1-8ebc-e9c00c461065',
        title: 'save story and publish [Kopia]',
        image: null,
        modificationTime: '2024-11-05T12:44:31Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'Anas'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 7,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '85679f49-309e-4a92-9d76-129358e40468',
        title: 'zaplanowane',
        image: null,
        modificationTime: '2024-11-05T12:44:31Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'Anas'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 6,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '40d82dd2-1e3c-4e65-bfa4-1017a00e5600',
        title: 'This is awesome Storyyyy',
        image: getImagePath(TestImage.FOREST_2, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:31Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'Azerbaijan'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 13,
            wordCount: 2,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '9906e331-50e9-4afa-827e-3f42e543bf4d',
        title: 'Common chameleon',
        image: getImagePath(TestImage.APARTMENT, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:31Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Reptiles', 'IUCN Red List least concern species', 'Chamaeleo', 'Mammals'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4175,
            wordCount: 661,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 4,
        },
    },
    {
        id: '423a4901-430c-4d93-9387-eb0ce24b0b37',
        title: 'Llama',
        image: getImagePath(TestImage.MOOSE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Quiz',
        author: null,
        source: 'Wikipedia',
        flags: ['Adult only', 'Hidden', 'Not news', 'Closed', 'Fotoalert', 'Sponsored', 'No ads'],
        topics: [
            'Mammals',
            'Domesticated animals',
            'Camelids',
            'Animal hair products',
            'Livestock',
            'Mammals of the Andes',
            'Mammals of Bolivia',
            'Mammals of Ecuador',
            'Mammals of Peru',
            'Pack animals',
            'Mammals described in 1758',
            'Taxa named by Carl Linnaeus',
            'test',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 22708,
            wordCount: 3571,
            editorialScore: null,
            tagsCount: 12,
            topicsCount: 13,
        },
    },
    {
        id: 'a279362a-7758-406d-88d7-71553c82ebe3',
        title: 'Czy wiesz że? Quiz tylko dla erudytów',
        image: getImagePath(TestImage.CASTLE, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Quiz',
        author: 'Piotr Łęgowski',
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Birds', 'Wiedza3'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 44,
            wordCount: 6,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '2b5a44a5-2839-4faf-864b-aca702674a69',
        title: 'The frilled-neck lizard',
        image: getImagePath(TestImage.CAR_4, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: null,
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Breathable', 'Living', 'Cold blooded', 'Funny'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1419,
            wordCount: 228,
            editorialScore: null,
            tagsCount: 3,
            topicsCount: 4,
        },
    },
    {
        id: '59bb13bc-68ac-4327-a5a9-4aa3a9b10909',
        title: 'save story and publish',
        image: null,
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['News', 'Dessert', 'Amphibians', 'Anas'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 7,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 4,
        },
    },
    {
        id: 'aa1bf8e7-a092-4261-8cfe-d101859564a2',
        title: 'Typography',
        image: null,
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Editorial Lists', 'jakiś tag1'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 9,
            wordCount: 2,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '55a6934a-8475-4784-87df-34f77a0b2a5e',
        title: 'Dingo',
        image: getImagePath(TestImage.CAR, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Article',
        author: null,
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Mammals', 'emoji'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 6897,
            wordCount: 832,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '5e24cdde-d33d-44c6-af17-92b75a8da91c',
        title: 'Article',
        image: null,
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Amphibians', 'Anas'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '84ad1dbf-7e07-4445-b952-c7f47eaf03ee',
        title: 'Peafowl',
        image: getImagePath(TestImage.CAR, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: null,
        author: 'Wiki',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Breathable', 'Flying', 'Birds'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1154,
            wordCount: 185,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 3,
        },
    },
    {
        id: '3b2e9230-bd78-4cfb-b3fc-ce6e7bd04f97',
        title: 'The sun bear. A bear found in tropical forest habitats of Southeast Asia',
        image: getImagePath(TestImage.CAR_2, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: null,
        author: 'Wiki',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Breathable', 'Strong', 'Furry', 'Big', 'Mammals'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 2616,
            wordCount: 445,
            editorialScore: null,
            tagsCount: 4,
            topicsCount: 5,
        },
    },
    {
        id: 'a08b9e4a-4a7c-4f08-a9ba-f35d19ea0f58',
        title: 'Tytuł story dla treści zewnętrznej',
        image: null,
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'News', 'Beef'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 4,
            wordCount: 1,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 3,
        },
    },
    {
        id: '0b3cc5ce-f9ca-4fb6-aa92-aee90c54bc41',
        title: 'Story with a lot of features. Part-1 [Kopia 1]',
        image: getImagePath(TestImage.SEA, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Article',
        author: 'Arkadiusz Staroń',
        source: 'Ring Publishing',
        flags: ['Disable autonext', "Editor's choice (deprecated)", 'Not news', 'No ads'],
        topics: [
            'Pulse2Demo',
            'News',
            'Birds',
            'Moszna Castle',
            'Algeria',
            'Mammals of North Africa',
            'Oscars 2021',
            'Wolverine',
            'Reptile Exhibition',
            'Business Insider Polska',
            'autoswiat.pl',
        ],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 640,
            wordCount: 86,
            editorialScore: null,
            tagsCount: 5,
            topicsCount: 11,
        },
    },
    {
        id: '53eb3695-a85b-4a8e-b1b4-20958ed0c71c',
        title: 'Keel-billed toucan',
        image: getImagePath(TestImage.JELLYFISH, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: null,
        author: 'Wiki',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Breathable', 'Birds'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 1112,
            wordCount: 195,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 2,
        },
    },
    {
        id: '6fb0273b-accc-4c95-a1b3-61594d6359fa',
        title: 'Hyacinth macaw',
        image: getImagePath(TestImage.FARM, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: null,
        author: 'Wiki',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Breathable', 'Animals', 'Flying'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 2066,
            wordCount: 357,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 3,
        },
    },
    {
        id: '857ed705-93ee-4aaa-bbd5-6e24638bc540',
        title: 'Hello World',
        image: getImagePath(TestImage.ORCHARD, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Article',
        author: null,
        source: 'Ring Publishing',
        flags: ['No ads'],
        topics: ['Pulse2Demo', 'Mammals', 'Ad Server', 'Chamaeleo'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 102,
            wordCount: 15,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 4,
        },
    },
    {
        id: 'b3c93dac-7c0a-4b18-bc21-09c453e04e76',
        title: 'Atlantic puffin',
        image: getImagePath(TestImage.CRAB, ImageSize.SMALL),
        modificationTime: '2024-11-05T12:44:29Z',
        kind: null,
        author: 'Wiki',
        source: 'Wikipedia',
        flags: ['No ads'],
        topics: ['Breathable', 'Birds', 'Flying'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 2641,
            wordCount: 460,
            editorialScore: null,
            tagsCount: 2,
            topicsCount: 3,
        },
    },
    {
        id: '4072174f-1fd0-4755-bfa7-f69947e1713f',
        title: 'tyt',
        image: null,
        modificationTime: '2024-11-05T12:44:29Z',
        kind: 'Article',
        author: null,
        source: 'Business Insider',
        flags: ['No ads'],
        topics: ['Recipes', 'Animals', 'Brown bear'],
        workflowStage: { name: 'Ready', color: '#04A03C' },
        status: 'PUBLISHED',
        metrics: {
            charactersCount: 9,
            wordCount: 3,
            editorialScore: null,
            tagsCount: 1,
            topicsCount: 3,
        },
    },
];
